// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TIS_NTHUML.Model
{
    public class ModelInput
    {
        [ColumnName("Source_Name"), LoadColumn(0)]
        public string Source_Name { get; set; }


        [ColumnName("VBmaxWD_F1"), LoadColumn(1)]
        public float VBmaxWD_F1 { get; set; }


        [ColumnName("VBmaxWD_F2"), LoadColumn(2)]
        public float VBmaxWD_F2 { get; set; }


        [ColumnName("VBmaxWD_F3"), LoadColumn(3)]
        public float VBmaxWD_F3 { get; set; }


        [ColumnName("VBmaxWD_F4"), LoadColumn(4)]
        public float VBmaxWD_F4 { get; set; }


        [ColumnName("VBsumWD_F1"), LoadColumn(5)]
        public float VBsumWD_F1 { get; set; }


        [ColumnName("VBsumWD_F2"), LoadColumn(6)]
        public float VBsumWD_F2 { get; set; }


        [ColumnName("VBsumWD_F3"), LoadColumn(7)]
        public float VBsumWD_F3 { get; set; }


        [ColumnName("VBsumWD_F4"), LoadColumn(8)]
        public float VBsumWD_F4 { get; set; }


        [ColumnName("VBWL_F1"), LoadColumn(9)]
        public float VBWL_F1 { get; set; }


        [ColumnName("VBWL_F2"), LoadColumn(10)]
        public float VBWL_F2 { get; set; }


        [ColumnName("VBWL_F3"), LoadColumn(11)]
        public float VBWL_F3 { get; set; }


        [ColumnName("VBWL_F4"), LoadColumn(12)]
        public float VBWL_F4 { get; set; }


        [ColumnName("CHnum_F1"), LoadColumn(13)]
        public float CHnum_F1 { get; set; }


        [ColumnName("CHnum_F2"), LoadColumn(14)]
        public float CHnum_F2 { get; set; }


        [ColumnName("CHnum_F3"), LoadColumn(15)]
        public float CHnum_F3 { get; set; }


        [ColumnName("CHnum_F4"), LoadColumn(16)]
        public float CHnum_F4 { get; set; }


        [ColumnName("CHsum_F1"), LoadColumn(17)]
        public float CHsum_F1 { get; set; }


        [ColumnName("CHsum_F2"), LoadColumn(18)]
        public float CHsum_F2 { get; set; }


        [ColumnName("CHsum_F3"), LoadColumn(19)]
        public float CHsum_F3 { get; set; }


        [ColumnName("CHsum_F4"), LoadColumn(20)]
        public float CHsum_F4 { get; set; }


    }
}
